<?php
$con=mysql_connect("localhost","root","MANI28ADMIN");
if(!$con)
{
	die("Could not connect".mysql_error());
}
mysql_select_db("DBMS",$con);


$sql="CREATE TABLE DEPARTMENT
(
ID VARCHAR(4) NOT NULL,
NAME VARCHAR(100),
PRIMARY KEY (ID)
)";
if (!mysql_query($sql,$con))
{
die('DEPARTMENT: ' . mysql_error());
}


$sql="CREATE TABLE STUDENT
(
ID INTEGER NOT NULL,
ROLL INTEGER NOT NULL,
FIRSTNAME VARCHAR(20),
MIDNAME VARCHAR(20),
LASTNAME VARCHAR(20),
DOB DATE,
GENDER VARCHAR(1),
FFN VARCHAR(20),
FMN VARCHAR(20),
FLN VARCHAR(20),
MFN VARCHAR(20),
MMN VARCHAR(20),
MLN VARCHAR(20),
YEAR INTEGER,
SEM INTEGER,
DID VARCHAR(5),
PASSWORD VARCHAR(10) NOT NULL,
CHECK (GENDER IN ('M','F')),
PRIMARY KEY (ID),
FOREIGN KEY (DID)
REFERENCES DEPARTMENT(ID)
)";
if (!mysql_query($sql,$con))
{
die('STUDENT: ' . mysql_error());
}
$sql="CREATE TABLE TEACHER
(
ID INTEGER NOT NULL,
FIRSTNAME VARCHAR(20),
MIDNAME VARCHAR(20),
LASTNAME VARCHAR(20),
GENDER VARCHAR(1),
DID VARCHAR(5) NOT NULL,
DESIGNATION VARCHAR(1),
PASSWORD VARCHAR(10) NOT NULL,
CHECK (DESIGNATION IN ('D','H','P','A','L')),
CHECK (GENDER IN ('M','F')),
PRIMARY KEY (ID),
FOREIGN KEY (DID)
REFERENCES DEPARTMENT(ID)
)";
if (!mysql_query($sql,$con))
{
die('TEACHER: ' . mysql_error());
}


$sql="CREATE TABLE ADDRESS
(
ID INTEGER NOT NULL,
LINE1 VARCHAR(100) NOT NULL,
LINE2 VARCHAR(100),
PO VARCHAR(20),
PIN INTEGER,
CITY VARCHAR(20),
STATE VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20) NOT NULL,
FOREIGN KEY (ID)
REFERENCES STUDENT(ID)
)";


if (!mysql_query($sql,$con))
{
die('ADDRESS: ' . mysql_error());
}
$sql="CREATE TABLE SPHONE
(
ID INTEGER NOT NULL,
NUMBER BIGINT,
TYPE VARCHAR(1),
CHECK (CATEGORY IN ('P', 'S')),
FOREIGN KEY (ID)
REFERENCES STUDENT(ID)
)";

if (!mysql_query($sql,$con))
{
die('Error PHONE: ' . mysql_error());
}
$sql="CREATE TABLE TPHONE
(
ID INTEGER NOT NULL,
NUMBER BIGINT,
TYPE VARCHAR(1),
CHECK (CATEGORY IN ('P', 'S')),
FOREIGN KEY (ID)
REFERENCES TEACHER(ID)
)";
if (!mysql_query($sql,$con))
{
die('Error PHONE: ' . mysql_error());
}

$sql="CREATE TABLE SEMAIL
(
ID INTEGER NOT NULL,
EMAIL VARCHAR(320),
TYPE VARCHAR(1),
CHECK (CATEGORY IN ('P', 'S')),
FOREIGN KEY (ID) 
REFERENCES STUDENT(ID)
)";
if (!mysql_query($sql,$con))
{
die('EMAIL: ' . mysql_error());
}

$sql="CREATE TABLE TEMAIL
(
ID INTEGER NOT NULL,
EMAIL VARCHAR(320),
TYPE VARCHAR(1),
CHECK (CATEGORY IN ('P', 'S')),
FOREIGN KEY (ID) 
REFERENCES TEACHER(ID)
)";
if (!mysql_query($sql,$con))
{
die('EMAIL: ' . mysql_error());
}

$sql="CREATE TABLE SUBJECT
(
CODE VARCHAR(8) NOT NULL,
NAME VARCHAR(150),
DID VARCHAR(5) NOT NULL,
CREDIT INTEGER,
CATEGORY VARCHAR(1),
CHECK (CATEGORY IN ('C', 'E')),
PRIMARY KEY(CODE),
FOREIGN KEY (DID)
REFERENCES DEPARTMENT(ID)
)";
if (!mysql_query($sql,$con))
{
die('SUBJECT: ' . mysql_error());
}

$sql="CREATE TABLE INSTRUCTOR
(
CODE VARCHAR(8) NOT NULL,
TID INTEGER NOT NULL,

FOREIGN KEY (TID)
REFERENCES TEACHER(ID),
FOREIGN KEY (CODE)
REFERENCES SUBJECT(CODE)
)";
if (!mysql_query($sql,$con))
{
die('INSTRUCTOR: ' . mysql_error());
}


$sql="CREATE TABLE RESULT
(
SID INTEGER NOT NULL,
CODE VARCHAR(10) NOT NULL,
POINTER INTEGER,
SEM INTEGER,
TID INTEGER NOT NULL,
PRIMARY KEY (SID,CODE),
FOREIGN KEY (SID)
REFERENCES STUDENT(ID),
FOREIGN KEY(TID)
REFERENCES TEACHER(ID),
FOREIGN KEY(CODE)
REFERENCES SUBJECT(CODE)
)";
if (!mysql_query($sql,$con))
{
die('RESULT: ' . mysql_error());
}




/*$sql="CREATE TRIGGER TEACH_TRIG 
AFTER INSERT ON TEACHER
FOR EACH ROW
BEGIN
UPDATE TEACHER SET PASSWORD=ID WHERE ID=ID;

END;
";
if (!mysql_query($sql,$con))
{
die('TEACH_TRIG: ' . mysql_error());
}


$sql="CREATE TRIGGER STU_DEL_TRIG 
AFTER DELETE ON TEACHER
FOR EACH ROW
BEGIN
UPDATE TEACHER SET PASSWORD=ID WHERE ID=ID;

END;
";
if (!mysql_query($sql,$con))
{
die('TEACH_TRIG: ' . mysql_error());
}
*/





mysql_close($con);
?>